version: '3.7'

services:
  rss_base:
    image: 'rss_base:latest'
    build:
      context: ./rss_base/.
      dockerfile: Dockerfile
    ports:
     - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certificate/aspnetapp.pfx
    volumes:
      - ./certificate:/certificate:ro
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - backend
  
  grpc_client:
    image: 'grpc_client:latest'
    build:
      context: ./Grpc_Client/.
      dockerfile: Dockerfile
    depends_on:
      - rss_base
    environment:
      - GrpcConfigurationOptions__LeafCertificateThumbString=${LEAF}
      - GrpcConfigurationOptions__IntermediateCertificateThumbString=${INTERMEDIATE}
      - GrpcConfigurationOptions__CertificatePinning=true
      - GrpcConfigurationOptions__url=https://host.docker.internal:443
      - GrpcConfigurationOptions__GrpcClientTimeOut=5
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - backend

  rest_client:
    image: 'rest_client:latest'
    build:
      context: ./Rest_Client/.
      dockerfile: Dockerfile
    depends_on:
      - rss_base
    environment:
      - RestClientConfigurationOptions__LeafCertificateThumbString=${LEAF}"
      - RestClientConfigurationOptions__IntermediateCertificateThumbString=${INTERMEDIATE}
      - RestClientConfigurationOptions__CertificatePinning=true
      - RestClientConfigurationOptions__url=https://host.docker.internal:443
      - RestClientConfigurationOptions__RestClientTimeOut=5
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - backend

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
  
networks:
  backend:
